### ISSUE TITLE
Add resistor into power feed to the LCD step up

### ISSUE THREAD

**Issue by schneider42** [muccc/Camp2015#100]
To provide some attenuation to the ~200 kHz noise it is producing.

If possible also increase the capacitor footprint to 0805.

**Comment by morawekj** [comment]
C809 ? auf 0805 ?

Wert Widerstand, welcher Strom, wegen Verlustleistung ?

**Comment by schneider42** [comment]
Ja, C809.

Ich habe 10 Ohm genommen. Verlustleistung bei 40 mA sind 20 mW

**Comment by morawekj** [comment]
done, 0402, kann 63 mW laut Datenblatt von Vishay
