### ISSUE TITLE
Add low pass filters to supply voltage of audio amp

### ISSUE THREAD

**Issue by schneider42** [muccc/Camp2015#101]
I think it is amplifying some noise when listening to the microphone

**Comment by morawekj** [comment]
Welchen Strom benötigt der Amp, irgend welche Werte bekannt ?

**Comment by schneider42** [comment]
Momentan unbekannt.

**Comment by morawekj** [comment]
Ist halt für die Bauteilbelastung relevant

**Comment by schneider42** [comment]
Muss heute abend noch gemessen werde.

**Comment by morawekj** [comment]
Done
