### ISSUE TITLE
Add low pass filters for audio DAC and ADC

### ISSUE THREAD

**Issue by schneider42** [muccc/Camp2015#102]
Just to have the option available. The microphone is a bit noisy at the moment

**Comment by morawekj** [comment]
Grenzfrequenz für Sprache oder Musik, 3 KHz Versus 20 KHz

**Comment by schneider42** [comment]
Ich schlage 20 kHz vor.

**Comment by schneider42** [comment]
Ah, moment:

20 kHz fuer den DAC, 3 kHz fuer den ADC

**Comment by morawekj** [comment]
Erledigt
