### ISSUE TITLE
Werte Widerstände Audio Amp und Buchse

### ISSUE THREAD

**Issue by morawekj** [muccc/Camp2015#104]
Neue Werte für Feedbackleitungen des Audioamps mitteilen, endgülige Buchsebelegung nötig

**Comment by schneider42** [comment]
Buchsenbelegung ist aktuell korrekt. Wir muessen nur entscheiden, ob wir einen oder beide Kanaele ansprechen wollen.

**Comment by schneider42** [comment]
Belegung ist auch getestet

**Comment by morawekj** [comment]
welche Postionen der Widerstände sind korrekt, ist im aktuellen Schaltplan nicht markiert, hast parallelschaltung der beiden Ohrhörer getestet ?

**Comment by schneider42** [comment]
Wir brauchen R910 und R913. Parallelschaltung habe ich noch nicht getestet

**Comment by morawekj** [comment]
OK die Werte der Widerstände fehlen dann noch

**Comment by morawekj** [comment]
Alles berechnet und eingefügt
