### ISSUE TITLE
Position of jack connector

### ISSUE THREAD

**Issue by loelkes** [muccc/Camp2015#124]
Hi,
der Kopfhöhreranschluss (3,5mm Klinke?) ist auf dem Bild auf einer anderen Stelle als auf dem EAGLE-Plan. Ich denke mal, dass das BIld noch ein Beta-Board war oder?
Ich baue nämlich gerade 3D CAD Dateien. Ich gehe davon aus, dass das EAGLE-File stimmt.
![screen shot 2015-07-13 at 04 49 11](https://cloud.githubusercontent.com/assets/231909/8641776/8da28f52-291a-11e5-9c14-901a12d71263.png)

**Comment by schneider42** [comment]
Yes that is correct. We moved the headset jack a bit on the final board. I will close the issue as soon as the final pictures of the design are available online.

**Comment by loelkes** [comment]
OK. This is enough for me and can be closed.
