### ISSUE TITLE
Case design

### ISSUE THREAD

**Issue by loelkes** [muccc/Camp2015#125]
Hallo,
ich habe mal ein Grundelement für eine Gehäuse designed und wollte testen ob das geht. Es soll verschiedene Versionen geben: Bumper (damit es gut liegt) und dann noch ein paar mehr oder weniger geöffnete Versionen.
Ich könnte euch eins mit der Post schicken oder habt ihr ein neues PCB, dass ich zum testen haben könnte?

Frage: ist es ein 1,6mm PCB?

Der Plan ist schon ein paar viele Cases vor dem Camp zu drucken damit dann vor Ort genug für alle gibt.

![screen shot 2015-07-17 at 19 14 55](https://cloud.githubusercontent.com/assets/231909/8752969/245a46e2-2cb8-11e5-8caa-a21b6f4faa68.png)

**Comment by morawekj** [comment]
Hallo,

so wie es aussieht kommen die neuen Muster am Mittwoch/Donnerstag an, gerne testen wir, ob es passt

in etwa 1.6, müsste mal in den Wagenaufbau schauen, muss mal Schneider anhauen.

Gruß Jan

**Comment by loelkes** [comment]
OK, ich schicke euch am Montag/Dienstag ein paar Samples. Magst du mir eine Adresse an obelix@entropia.de schreiben?
Grüße
Obelix

**Comment by schneider42** [comment]
Ja, ist ein 1.6 mm Lagenaufbau
