### ISSUE TITLE
Check heatsinking of the VREGs

### ISSUE THREAD

**Issue by schneider42** [muccc/Camp2015#32]

**Comment by amperpirat** [comment]
- no solder mask around the MAX15101
- Thermal vias on and/or near the balls
- huge copper areas around the MAX15101
- calculations / numbers:
  Tj_max=160°C --> thermal shutdown (with hysteresis of 15°C)
  SOA: I_max >=1A (max. delta V = 4.2V-3.3V) (DS page 8)
