### ISSUE TITLE
change type of flash chip to winbond type

### ISSUE THREAD

**Issue by schneider42** [muccc/Camp2015#69]
We might also need to change the package to the more available 5.08 mm SO8

**Comment by morawekj** [comment]
Immer noch aktuell ?

**Comment by schneider42** [comment]
Muss ich nochmal pruefen. Ich glaube in der BOM ist es noch falsch aber im Schaltplan sollte es passen.

**Comment by morawekj** [comment]
Im Layout und Schaltplan passt es

**Comment by morawekj** [comment]
Funktion OK, close
